import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync } from "fs";
import { dirname } from "path";

const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outfile = "/Users/csprunger/Documents/obsidian/machine-learning/.obsidian/plugins/image-inline-v2/main.js";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],  // Updated path
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "sharp",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: outfile,
});

// Copy manifest.json to output directory
function copyManifest() {
    const outDir = dirname(outfile);
    copyFileSync("manifest.json", `${outDir}/manifest.json`);
    console.log("Copied manifest.json to output directory.");
}

if (prod) {
    await context.rebuild();
    copyManifest();
    console.log("Production build completed.");
    process.exit(0);
} else {
    await context.watch();
    copyManifest();
    console.log('Watching for changes...');
}
